Update to use scalar adds.
Receives a runtime exception:
  InaccessibleTensorError: tf.Graph captured an external symbolic
tensor. The symbolic tensor <tf.Tensor 'while_1/add_6:0' shape=()
dtype=float32> is captured by FuncGraph(name=update_state,
id=5843251600), but it is defined at FuncGraph(name=while_1_body_2968,
id=5835556032). A tf.Graph is not allowed to capture symoblic tensors
from another graph. Use return values, explicit Python locals or
TensorFlow collections to access it. Please see
https://www.tensorflow.org/guide/function#all_outputs_of_a_tffunction_must_be_return_values
for more information.